apiVersion : apps/v1
kind: Deployment
metadata:
  name: dontstarve 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dontstarve
  template:
    metadata:
      labels:
        app: dontstarve 
    spec:
      containers:
        - name: dontstarve 
          image: dontstarve.azurecr.io/dontstarve
          ports:
          - containerPort: 10999
            name: port0
            protocol: UDP
          - containerPort: 11000
            name: port1
            protocol: UDP
          - containerPort: 12346
            name: port2
            protocol: UDP
          - containerPort: 12347
            name: port3
            protocol: UDP
