apiVersion : apps/v1
kind: Deployment
metadata:
  name: dontstarve 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dontstarve
  template:
    metadata:
      labels:
        app: dontstarve 
    spec:
      containers:
        - name: dontstarve 
          image: dontstarve.azurecr.io/dontstarve
          ports:
          - containerPort: 10999-11000/udp 12346-12347/udp