apiVersion: v1
kind: Service
metadata:
    name: dontstarve
spec:
    type: LoadBalancer
    ports:
    - port: 10999
      name: port0
      protocol: udp
    - port: 11000
      name: port1
      protocol: udp
    - port: 12346
      name: port2
      protocol: udp
    - port: 12347
      name: port3
      protocol: udp
    selector:
        app: dontstarve
